# Generated by Django 4.2.3 on 2023-08-30 14:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_customer_is_seller_product_seller'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='is_seller',
        ),
        migrations.RemoveField(
            model_name='product',
            name='seller',
        ),
    ]
