# Generated by Django 4.2.3 on 2023-08-30 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0009_seller_product_seller'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='is_seller',
            field=models.BooleanField(default=False),
        ),
    ]
